### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ironman20075** [Nukkit-coders/NPC#15]
Hi i got this error, if I run /npc addcmd 6 takemoney 100

[36m13:34:47[m [[m[5;1;31mFATAL[m[m] Unhandled exception executing command "npc addcmd 6 takemoney 100" in npc: java.lang.NullPointerException

at idk.plugin.npc.CommandHandler.handle(CommandHandler.java:84)

at idk.plugin.npc.NPC.onCommand(NPC.java:101)

at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)

at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)

at cn.nukkit.Server.dispatchCommand(Server.java:764)

at cn.nukkit.Player.handleDataPacket(Player.java:2812)

at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source)

at java.util.ArrayList.forEach(ArrayList.java:1257)

at cn.nukkit.network.Network.processPackets(Network.java:268)

at cn.nukkit.network.Network.processBatch(Network.java:251)

at cn.nukkit.Player.handleDataPacket(Player.java:2102)

at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source)

at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:156)

at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)

at cn.nukkit.network.Network.processInterfaces(Network.java:152)

at cn.nukkit.Server.tick(Server.java:1137)

at cn.nukkit.Server.tickProcessor(Server.java:916)

at cn.nukkit.Server.start(Server.java:893)

at cn.nukkit.Server.<init>(Server.java:578)

at cn.nukkit.Nukkit.main(Nukkit.java:112)

[36m13:34:47[m [[m[1;31mERROR[m[m] Throwing

java.lang.NullPointerException: null

at idk.plugin.npc.CommandHandler.handle(CommandHandler.java:84) ~[NPC-2.3.2.jar:?]

at idk.plugin.npc.NPC.onCommand(NPC.java:101) ~[NPC-2.3.2.jar:?]

at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33) ~[nukkit-1.16.jar:?]

at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.16.jar:?]

at cn.nukkit.Server.dispatchCommand(Server.java:764) ~[nukkit-1.16.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:2812) ~[nukkit-1.16.jar:?]

at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[GAC-1.0.jar:?]

at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_212]

at cn.nukkit.network.Network.processPackets(Network.java:268) [nukkit-1.16.jar:?]

at cn.nukkit.network.Network.processBatch(Network.java:251) [nukkit-1.16.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:2102) [nukkit-1.16.jar:?]

at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]

at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:156) [nukkit-1.16.jar:?]

at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-1.16.jar:?]

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65) [nukkit-1.16.jar:?]

at cn.nukkit.network.Network.processInterfaces(Network.java:152) [nukkit-1.16.jar:?]

at cn.nukkit.Server.tick(Server.java:1137) [nukkit-1.16.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:916) [nukkit-1.16.jar:?]

at cn.nukkit.Server.start(Server.java:893) [nukkit-1.16.jar:?]

at cn.nukkit.Server.<init>(Server.java:578) [nukkit-1.16.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.16.jar:?]

**Comment by PetteriM1** [comment]
Fixed in 2.4.0
